pipeline {
    agent any

    environment {
        AWS_DEFAULT_REGION    = "us-east-1"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                url: 'https://github.com/Akashbora02/Git.git'
            }
        }

        stage('Terraform Init') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-creds'
                ]]) {
                dir('CreateEKSWithJenkins'){
                sh '''
                  terraform init
                '''
                }
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-creds'
                ]]) {
                dir('CreateEKSWithJenkins'){
                sh '''
                  terraform plan
                '''
                }
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-creds'
                ]]) {
                dir('CreateEKSWithJenkins'){
                sh '''
                  terraform apply -auto-approve
                '''
                }
                }
            }
        }
    }
    post {
        success {
            echo 'EKS creation successful, triggering Destroy Pipeline'
            build job: 'Destroy-EKS-Pipeline', wait: false
        }
    }
}
